language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: tROg8+JuIpPmm4WjmjBrEDRY/o2vV//TXd8Du/vjdfcAI2Pb59e9INLWZboooB0Ue70+NKzOeDbpakQsBaqG5lg0J6q45zAUf5SMVhMpFrLOF1B4lG8pcPAcLnvpryFbw/9fjOH+VqlgiQxBcTP4o7bofIKoeA/+Q0rOHIk3KfyIBuVKPTm6EGCKPooO53ttiqC7hZlq1SQAUF/aNbK3F1b0x+CVCZ/iytzFqov3IfQC75V1kMhMHQ3WlpeFSVJwKkMpmSfBlOTDQarHhpfjnpgPQbzyFcwqAAHzS+pr4Kx+22a4uiLLQSoC+gSKGwLf1zBurmfa/NVPb1GcUdXoXWSBO+AXb+hWny+OfIdgoB1JgKsjAWKiRACL3e1H2XbJPkEydyiP2VawVW+0eeVvcfX4JG90dRWXA82hi/GCSn+cCHBJeRlBeWs6qCDc+spyTXOtsc5OjVZGYejj497XhSJ3wexcpGIgvvLI4BFyVwOi1C6mXwbxkXbGgUbHdaQWbyEiu3lDWLx8gR+rP/Q8ykhla3Uhuwy6oxtQAKEcL+0lGuZmzjdKdlkls749CEngfaEkqiF6gGzIUeU+322plLmN1kOUzFcGIq0fM5xVUWuHreHXffyxUGCKX+JRAoyDy6MnyUYEakxVZBCDHKy5SOsItM6TarVndXPPFADuoUI=
  app: calm-lowlands-64387
  on:
    repo: sobhit000/dream-journal-app-client
